# Generated by Django 2.1.4 on 2018-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweeter_user', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('create', models.DateField()),
                ('locate', models.TextField()),
                ('num_word', models.IntegerField()),
                ('num_letter', models.IntegerField()),
            ],
        ),
    ]
