# Generated by Django 2.1.4 on 2018-12-09 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweeter_user', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('create', models.DateField()),
                ('locate', models.TextField()),
                ('num_word', models.IntegerField()),
                ('num_letter', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.TextField(default='km2MppUbx5dhTXYEF0WNmGRyT')),
                ('consumer_secret', models.TextField(default='KqpgTK4O1UliFhpOSMrdCRRvWJlSoYarbNYXx51cbay3Qqrr7n')),
                ('access_token', models.TextField(default='1071105441952923648-kZ4PzWqL1qhT8nWZWI3h6zHvPd0cD8')),
                ('access_token_secret', models.TextField(default='MwOrSDreqI6qZiPnpqj8pDd30cqbtRkp6cJIaBR9zd8hh')),
                ('filter_key', models.TextField(default='#Python')),
                ('is_search', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
