# Generated by Django 2.1.4 on 2018-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='locate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='num_letter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='num_word',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweeter_user',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
