# Generated by Django 2.1.4 on 2018-12-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.TextField(default='km2MppUbx5dhTXYEF0WNmGRyT')),
                ('consumer_secret', models.TextField(default='KqpgTK4O1UliFhpOSMrdCRRvWJlSoYarbNYXx51cbay3Qqrr7n')),
                ('access_token', models.TextField(default='1071105441952923648-kZ4PzWqL1qhT8nWZWI3h6zHvPd0cD8')),
                ('access_token_secret', models.TextField(default='MwOrSDreqI6qZiPnpqj8pDd30cqbtRkp6cJIaBR9zd8hh')),
                ('filter_key', models.TextField(default='#Python')),
            ],
        ),
    ]
