# Generated by Django 2.1.4 on 2018-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0002_userconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='is_search',
            field=models.BooleanField(default=False),
        ),
    ]
