# Generated by Django 2.1.4 on 2018-12-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0002_auto_20181210_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tag',
            field=models.TextField(blank=True, default='#Python', null=True),
        ),
    ]
