# Generated by Django 2.0.9 on 2018-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_tweet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
